#!/usr/bin/env bash
# shellcheck shell=bash
#
# Netflix regional path allowlist for:
#   site:netflix.com/<country>/title
#
# Used by: NETFLIX_CATALOG_REGION in workflows/netflix-search
# Fallback: BRAVE_COUNTRY when NETFLIX_CATALOG_REGION is empty/invalid
#
# Generated by scripts/netflix-country-probe.sh
# Generated at: 2026-02-15 13:34:51 UTC
#
# Notes:
# - Keep codes lowercase.
# - us intentionally remains global (site:netflix.com/title).

NETFLIX_REGIONAL_TITLE_COUNTRIES=(
  "ar"
  "at"
  "au"
  "be"
  "br"
  "ca"
  "ch"
  "cl"
  "co"
  "cz"
  "de"
  "dk"
  "eg"
  "es"
  "fi"
  "fr"
  "gb"
  "gr"
  "hk"
  "hu"
  "id"
  "ie"
  "il"
  "in"
  "it"
  "jp"
  "kr"
  "mx"
  "my"
  "nl"
  "no"
  "nz"
  "pe"
  "ph"
  "pl"
  "pt"
  "ro"
  "sa"
  "se"
  "sg"
  "th"
  "tr"
  "tw"
  "ua"
  "vn"
  "za"
)

nfs_country_uses_regional_title_path() {
  local country="${1:-}"
  local code
  for code in "${NETFLIX_REGIONAL_TITLE_COUNTRIES[@]}"; do
    if [[ "$code" == "$country" ]]; then
      return 0
    fi
  done
  return 1
}
